import type { Metadata } from "next"
import { Fellix } from "@/styles/fonts"
import "@/styles/globals.css"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn("min-h-screen bg-background font-sans antialiased")} ${
          Fellix.className
        }`}
      >
        {children}
      </body>
    </html>
  )
}
